### ISSUE TITLE
better validation approach for "assign to"- multiple checkbox validation 

### ISSUE THREAD

**Issue by Ethan-LN** [tobiturner/to-do-list#33]
Problem: 
(1) Customised bootstrap classes can not deal with "at least one checkbox checked". Wrote a script separately for the "invalid feedback" that did not fit the bootstrap class and browser default validation format. 
Propose: 
(1)  Use the animation icon for the "valid" and "invalid" feedback to replace the "browser alert" 
(2) Ask the instructors to identify the problems for the implementations from other versions. and find out what is the best approach in the industry? 
![Screen Shot 2022-11-01 at 12 08 05](https://user-images.githubusercontent.com/71419743/199138650-4cbc0dd4-4f29-4760-af50-ec9343fbcdca.png)

**Comment by x107** [comment]
@Ethan-LN your solution of validating checkboxes is fine and works well.

You could also use _higher order_ function provider by javascript to traverse the checkboxes element array 

Example:
`
const checkboxes = document.getElementsByName('person');

const hasChecked = Array.from(checkboxes).filter(e => !!e.checked).length > 0;

if(!hasChecked) {
  alert("Please check at least 1 person");
}

`

We first convert the DOM elements into an javascript array, which providers the "higher-order" filter function. It takes each array element as parameter, and return a value via the arrow expression `=>`.

**Comment by Ethan-LN** [comment]
Thanks for the code demo!  It is a better approach with a higher-order function.

**Comment by Ethan-LN** [comment]
> Thanks for the code demo! It is a better approach with a higher-order function.
